url: https://bwits.github.io
baseurl:

# Site settings
title: bwits.github.io
email: ozbillwang@gmail.com
description: "bwits.github.io automates DevOps and Ops by creating rather neat PaaS and Big Data components on its own hybrid multicloud"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
